# Generated by Django 6.0.2 on 2026-03-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='films/', verbose_name='Постер')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'films',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='films_time_cr_5f03d2_idx')],
            },
        ),
    ]
