# Generated by Django 6.0.2 on 2026-06-02 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя режиссера')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('oscars_count', models.IntegerField(default=0, verbose_name='Количество Оскаров')),
                ('m_count', models.IntegerField(blank=True, default=0, verbose_name='Счетчик наград')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='URL')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='films/', verbose_name='Постер')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('directors', models.ManyToManyField(blank=True, related_name='films', to='films.director', verbose_name='Режиссёры')),
                ('genres', models.ManyToManyField(related_name='films', to='films.genre', verbose_name='Жанры')),
                ('tags', models.ManyToManyField(related_name='films', to='films.tagpost', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'films',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='FilmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет ($)')),
                ('box_office', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сборы ($)')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('filming_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место съемок')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='films.films', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Технические детали',
                'verbose_name_plural': 'Технические детали',
                'db_table': 'film_details',
            },
        ),
        migrations.CreateModel(
            name='FilmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='films.filmcomment', verbose_name='Родительский комментарий')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='films.films', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'film_comments',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='FilmCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactor_key', models.CharField(db_index=True, max_length=150, verbose_name='Ключ реакции')),
                ('value', models.SmallIntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Реакция')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='films.filmcomment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Реакция на комментарий',
                'verbose_name_plural': 'Реакции на комментарии',
                'db_table': 'film_comment_reactions',
                'constraints': [models.UniqueConstraint(fields=('comment', 'reactor_key'), name='unique_comment_reactor')],
            },
        ),
        migrations.CreateModel(
            name='FilmRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_key', models.CharField(db_index=True, max_length=150, verbose_name='Ключ оценившего')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='films.films', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Оценка фильма',
                'verbose_name_plural': 'Оценки фильмов',
                'db_table': 'film_ratings',
                'constraints': [models.UniqueConstraint(fields=('film', 'rater_key'), name='unique_film_rater')],
            },
        ),
        migrations.AddIndex(
            model_name='films',
            index=models.Index(fields=['-time_create'], name='films_time_cr_5f03d2_idx'),
        ),
    ]
