# Generated by Django 6.0.2 on 2026-03-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя режиссера')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('oscars_count', models.IntegerField(default=0, verbose_name='Количество Оскаров')),
                ('m_count', models.IntegerField(blank=True, default=0, verbose_name='Счетчик наград')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='films', to='films.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='films.director', verbose_name='Режиссер'),
        ),
        migrations.CreateModel(
            name='FilmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Бюджет ($)')),
                ('box_office', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сборы ($)')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMDB ID')),
                ('filming_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место съемок')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='films.films', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Технические детали',
                'verbose_name_plural': 'Технические детали',
                'db_table': 'film_details',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.tagpost', verbose_name='Теги'),
        ),
    ]
