# Generated by Django 6.0.2 on 2026-05-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='films',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='films', to='films.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='films.director', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='filmdetails',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='films.films', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='films',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='films',
            index=models.Index(fields=['-time_create'], name='films_time_cr_5f03d2_idx'),
        ),
    ]
