# Generated by Django 6.0.2 on 2026-03-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_category_director_tagpost_films_cat_films_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmdetails',
            name='imdb_id',
        ),
    ]
