# Generated by Django 6.0.2 on 2026-05-29 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_filmrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdetails',
            name='box_office',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сборы ($)'),
        ),
        migrations.AlterField(
            model_name='filmdetails',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет ($)'),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='films',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='FilmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='films.films', verbose_name='Фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='films.filmcomment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'film_comments',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='FilmCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactor_key', models.CharField(db_index=True, max_length=150, verbose_name='Ключ реакции')),
                ('value', models.SmallIntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Реакция')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='films.filmcomment', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Реакция на комментарий',
                'verbose_name_plural': 'Реакции на комментарии',
                'db_table': 'film_comment_reactions',
                'constraints': [models.UniqueConstraint(fields=('comment', 'reactor_key'), name='unique_comment_reactor')],
            },
        ),
    ]
