# Generated by Django 6.0.2 on 2026-05-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_remove_moderator_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
